### PR TITLE
Added method each_as_array(). Is like a recursive as_array() for databas...

### PR DESCRIPTION
**Pull request by alejandroiglesias**
...e results.

### CODE REVIEW

**Comment by alejandroiglesias** [comment]
Pull request targeted at branch 3.2/master and should be 3.2/develop.

**Comment by shadowhand** [comment]
This is invalid anyways, if you don't want the results as objects, use: `$query->as_object(FALSE)->execute()->as_array()`.

**Comment by alejandroiglesias** [comment]
Oh, great info! Thank you very much Woody!

2011/12/2 Woody Gilk <
reply@reply.github.com

**Comment by alejandroiglesias** [comment]
Ohh, but you can't use that with models, just with Database_Builder.
My proposal is for Database_Result, so we can do:
`$users_array = ORM::factory('user')->find_all()->each_as_array();`

**Comment by ernestas** [comment]
@alejandrogarciaiglesias

http://forum.kohanaframework.org/discussion/9488/oop-design-question-where-should-as_array_recursive-go
http://dev.kohanaframework.org/issues/4193

**Comment by alejandroiglesias** [comment]
Thank you very much!

2011/12/6 Ernestas Lisauskas <
reply@reply.github.com

**Comment by alejandroiglesias** [comment]
So why there is a as_array() method if Database_Result shouldn't take care of data format?

**Comment by deeceefar2** [comment]
This is what I use to accomplish this:

$data_as_array = array_map( create_function( '$obj', 'return method_exists($obj,"as_array") ? $obj->as_array() : $obj;'), ORM::factory('user')->find_all()->as_array());

This should accomplish what you want though it isn't pretty.

**Comment by alejandroiglesias** [comment]
Not pretty!

**Pull request closed without merging**
