### PR TITLE
Add composer.json to support installing with composer.

### PR DESCRIPTION
**Pull request by tmihalik**

### CODE REVIEW

**Comment by zeelot** [comment]
we already have a composer.json file. I'll merge all the 3.3 branches to 3.4 this weekend, sorry for the delay.

**Comment by tmihalik** [comment]
next weekend? :)

**Comment by zeelot** [comment]
nah, doing it right now! thanks for the reminder :)

**Comment by tmihalik** [comment]
thanks, now if it could be visible in packagist.org that would be heaven :)

**Comment by zeelot** [comment]
hmm doesn't it pick it up?

**Comment by zeelot** [comment]
I see a 3.4 develop here https://packagist.org/packages/kohana/database

**Comment by tmihalik** [comment]
That's fine, thanks!

**Pull request closed without merging**
