### PR TITLE
Add support for geometry field type in MySQL

### PR DESCRIPTION
**Pull request by rjmackay**
Adds geometry to Database_MySQL::datatype()

### CODE REVIEW

**Comment by zeelot** [comment]
Could you file a ticket in redmine and link this to it? Cheers.

**Comment by rjmackay** [comment]
Filed a ticket: http://dev.kohanaframework.org/issues/4745

**Comment by rjmackay** [comment]
Ping - @Zeelot any update on this?

**Comment by brianherbert** [comment]
This would be huge for anything geospatial built in Kohana.

**Comment by zeelot** [comment]
Thanks!

**Pull request merged**
