### PR TITLE
Sanitize input to offset() and limit()

### PR DESCRIPTION
**Pull request by jzskca**
See http://dev.kohanaframework.org/issues/4766.

### CODE REVIEW

**Comment by samwilson** [comment]
Those should be `NULL` not `null`, as per http://kohanaframework.org/3.3/guide/kohana/conventions#constants

:-)

**Comment by dm** [comment]
The comparison on the ternary operator should always be inside parenthesis as well.

Watch out for operator priority or you're sure to shoot yourself in the foot ;)

**Comment by jzskca** [comment]
@samwilson: I totally spaced on that. Thanks!

@dm: I wasn't aware that that was required. Thanks for the heads-up. Simple comparisons don't run afoul of PHP's take on the ternary operator, but I learned my lesson about nested ternary operators a long time ago.

Thanks guys :)

**Comment by dm** [comment]
@jzskca Not only that (nested ternary operator associativity differing from C/C++) but I've come across a bug introduced where a second condition was added without also adding parenthesis, while using OR for comparison, such as:

```
$var = 0;

$a = $var == true ? '1' : '2';
$x = $var == 1 OR $var == true ? '1' : '2';
$y = ($var == 1 OR $var == true) ? '1' : '2';

var_dump($a); // '2'  <-- Original
var_dump($x); // true <-- OPS
var_dump($y); // '2'  <-- What the developer intended while inserting a second comparison with bool (=
```

NOTE that using comparison OR has lower precedence than ternary operator; i.e. comparison using || would have worked here regardless of using parenthesis or not! :8ball:

Hence the use of parenthesis is encouraged! :laughing:

**Comment by acoulton** [comment]
@jzskca thanks for this contribution and sorry it was left open so long. I've merged manually to 3.3/develop in 6e14f399832 as this PR was targeted to 3.3/master.

**Pull request closed without merging**
