### PR TITLE
#2009, implemented

### PR DESCRIPTION
**Pull request by jshaw86**
Isaiah, per our conversation on irc, I believe I got all my changes merged into this commit.

Just quick overview API changes are as follows:
function on($op,$eq,$op2,$conjunction = "AND") //added 4th conjunction param
function or_join_close() //alias of or_where_close
function and_join_close() //alias of and_where_close
function join_close() //you get the idea
function or_join_open()
function and_join_open()
function join_open()

Let me know if you want to discuss. -Jordan

### CODE REVIEW

**Comment by shadowhand** [comment]
I think `or_join_open` and friends need to be named `or_on_open` instead, since you are doing `ON` operations, not `JOIN` operations.

**Comment by shadowhand** [comment]
And please remove jshaw86/database@067b2a716a8dafd3aa8e7b6221d26fe80fd74438, we don't want your local .gitingore file.

**Comment by jshaw86** [comment]
my bad on the .gitignore, that's from a script i made, it's a pretty standard ignore file imo though. 

I'm fine with whatev for API names, they don't matter to me, I was just trying to get it implemented for work.

**Comment by shadowhand** [comment]
Multiple issues with this pull request:
1. It is not up to date with current 3.1/master and has merge conflicts.
2. It references JP_Query_Builder, which is not a Kohana class.
3. As previously mentioned, method names need to be changed.
4. It does not actually implement #[2009](http://dev.kohanaframework.org/issues/2009), which was about adding `and_on` and `or_on` conditions.

The aim (as I understand it) of #[2009](http://dev.kohanaframework.org/issues/2009) is to allow `JOIN t1 ON (t1.foo = t2.foo OR t1.bar = t2.bar)`. As far as I can tell, your commits do not implement this, although they implement a bunch of other stuff.

**Comment by jshaw86** [comment]
I got caught up with work, didn't get around to implementing the API changes you requested. 

I'll have to pull down 3.1 and check the merge conflicts. I'll work on it tonight, and get back to you tonight.

**Pull request closed without merging**
