### PR TITLE
Added MySQLi classes

### PR DESCRIPTION
**Pull request by kohenkatz**
Some new server setups are configured without support for the MySQL PHP extension which will be removed in PHP 5.4.  Even for those who still have the MySQL driver, PHP recommends using MySQLi anyway.

### CODE REVIEW

**Comment by shadowhand** [comment]
All pull requests must be targeted against a "develop" branch (currently `3.3/develop`), which the Kohana build bot will be warning you about shortly.

**Comment by isaiahdw** [comment]
Also make sure you include the issue number in your pull request so we can make sure it doesn't get lost. I added it here: http://dev.kohanaframework.org/issues/3898

**Comment by kiall** [comment]
Crap - I have no idea what I just clicked

**Comment by kiall** [comment]
Okay - It looks like nothing changed somehow? 

Did this PR have any commits left in it?

**Comment by kohenkatz** [comment]
Nothing happened because I reverted my fork's 3.2 to the way it had been before and put my change only in the 3.3 branch.  I was not sure if there is a way to undo a pull request.

**Comment by kiall** [comment]
Right, that explains a lot :)

Not entirely sure how I reopened and merged this with one accidental click of the mouse!

**Pull request merged**
