### PR TITLE
Incorrect usage of UNION and ORDER BY without parenthesis

### PR DESCRIPTION
**Pull request by misterx**
When use ORDER BY with UNION, give error Incorrect usage of UNION and ORDER BY. http://stackoverflow.com/a/6732697

### CODE REVIEW

**Comment by kwn** [comment]
+1

**Comment by shadowhand** [comment]
Does this have a redmine issue?

**Comment by misterx** [comment]
No

**Comment by acoulton** [comment]
@misterx thanks for this contribution and sorry it's been left open so long. We'd need to take this into 3.3/develop rather than 3.3/master - I can apply that manually rather than asking you to close and reopen but can you confirm that the new syntax is valid in all the supported database engines? SQL isn't my strong point.

**Comment by enov** [comment]
I guess it's a :+1: from me. Regarding the syntax, it just adds parenthesis around the `SELECT` sub-queries, in order to remove the ambiguity. That should be supported by all the db engines.

**Comment by acoulton** [comment]
@misterx @enov thanks - applied to 3.3/develop in c53d8aaa

**Pull request closed without merging**
