### PR TITLE
INSERT INTO syntax does not allow table aliasing

### LINKED ISSUE #79: Insert query builder allows to use table alias in INSERT ... SELECT ... construction
I'm creating standalone query builder based on kohana database module. I fugured out that Insert Query Builder allows to use table alias while using select subquery instead of array values. This causes sql syntax error.

Solution:
Throw an exception during insert query compilation if $this->_table is array

``` php
// Insert class
        if (is_array($this->_values))
        {
            //[...]
        }
        else
        {
            if (is_array($this->_table)) {
                throw new Exception('Cannot use table alias with INSERT INTO ... SELECT ... construction');
            }
            // Add the sub-query
            $query .= (string) $this->_values;
        }
```

### PR DESCRIPTION
**Pull request by enov**
Closes #79 

This PR disallows anything but a string for an `INSERT INTO` table name. Specifically it does not allow table name aliasing anymore.

### CODE REVIEW

**Comment by kemo** [comment]
This is cool, I'd just remove the `{}` around that exception because we don't really do that with single line terminating condition statements (`return`, `die`, `throw`, `break`, `continue`)

**Comment by enov** [comment]
Thanks @kemo :) I see what you mean. I'll fix that soon.

**Comment by enov** [comment]
Can you please check now?

**Comment by kemo** [comment]
:+1:

**Comment by enov** [comment]
Thanks for reviewing @kemo .

**Pull request merged**
