### PR TITLE
Accessing to connection object

### PR DESCRIPTION
**Pull request by devmach**
Kohana's DB module hasn't got any real support for prepared statements. If we're using PDO driver, while we're enjoying Kohana goodies, we can also have "real" prepared statements etc.

This patch basicly gives user access to connection object.

### CODE REVIEW

**Comment by kiall** [comment]
The inline docs are incorrect, the connection property may it may not be a PDO instance.

It would be more accurate to remove the PDO (and pgsql) specifics since this class is database agnostic.

**Comment by kiall** [comment]
(...but I would leave the usage example at L201->L205)

**Comment by cbandy** [comment]
Why not just add a `prepare_statement()` method to `Database_PDO`?

**Comment by cbandy** [comment]
That is, I would prefer `PDO` functionality be added to `Database_PDO`.

**Comment by devmach** [comment]
I'm sorry, may bad . If you think too giving access to a connection handler/link is a logical way, i'll fix inline docs and make another pull request.

useless ps: this patch was intended use in-house and other than PDO is kind of no-go, that's why it's PDO ( and postgresql centric )

**Comment by devmach** [comment]
@cbandy hmm, prepare_statement() method could be better

**Comment by devmach** [comment]
I've implemented `prepare_statement()` and `last_insert_id()` methods to Database_PDO.

**Pull request closed without merging**
