### PR TITLE
Database Driver For Auth

### PR DESCRIPTION
**Pull request by justnorawr**

### CODE REVIEW

**Comment by isaiahdw** [comment]
Did you make a feature request for this database auth driver on our [issue tracker](http://dev.kohanaframework.org/projects/kohana3/activity)? If not, please create a new feature request there and link to this pull request so it doesn't get lost.

**Comment by justnorawr** [comment]
Okay, was not aware of that. Thank You!

**Comment by justnorawr** [comment]
Added feature request a little while ago. Any idea if this is going to get merged?

**Comment by craig-sparks** [comment]
This should be set for the develop branch, not master.

**Comment by zeelot** [comment]
Sorry yeah this should be for `3.4/develop` but I also don't want to complicate the database module with more code to maintain :(.

I'm closing the pull request but only because it's for the wrong branch. Could you please link to the redmine ticket if you made one? We should leave that open for feedback and see if we want this in `3.4.0`.

**Comment by craig-sparks** [comment]
http://dev.kohanaframework.org/issues/4574 is the ticket @Zeelot

**Comment by zeelot** [comment]
Ok thanks I'll leave a note there.

**Pull request closed without merging**
