### PR TITLE
Update Join.php

### PR DESCRIPTION
**Pull request by BlackScorp**
Enabled feature to use something like

SELECT column1,column2 FROM table JOIN table2 JOIN table3

### CODE REVIEW

**Comment by cbandy** [comment]
The SQL standard requires a join specification (ON or USING) unless the join is a NATURAL join or CROSS join. Also, a JOIN without a join type is an INNER join.

So, the code is probably correct to support NATURAL and CROSS joins, but your examples are not. If you are using this SQL, I would recommend changing it to a CROSS JOIN or adding the other tables using `from()`.

**Comment by zombor** [comment]
This would need an issue in our issue tracker as well, with the commit referencing the issue.

**Comment by BlackScorp** [comment]
ah ok then i open new issue on issue tracker and make a pull request to 3.4/develop branch? since 3.3 is already released?

**Comment by zombor** [comment]
Yes, this would be a 3.4 change, but it sounds like it needs to be discussed more.

**Comment by BlackScorp** [comment]
well this is just one line of code:D why discuss?

**Comment by acoulton** [comment]
@BlackScorp sorry that this has been left open so long. It looks like this is a new feature proposal - in which case as above it would need to be targeted to 3.4/develop and we'd need a more detailed commit message and unit tests covering the new behaviour. 

As it can't be merged as-is, I'll close this now but please do reopen if you wish to discuss it further.

**Pull request closed without merging**
