### PR TITLE
PDO driver should call set_charset in connect method

### PR DESCRIPTION
**Pull request by ljyf5593**
PDO driver should call set_charset in connect method.

### CODE REVIEW

**Comment by cbandy** [comment]
http://dev.kohanaframework.org/issues/4668
#54
#51

**Comment by ljyf5593** [comment]
body { font-family:'宋体'; font-size:13px}understand, but the config file config/database.php should be changed to response this issues.在 Tue, 14 Jan 2014 01:19:51 +0800，Chris Bandy notifications@github.com 写道:http://dev.kohanaframework.org/issues/4668

**Comment by pocesar** [comment]
spent 1 day trying to find out what the problem was in my code and database, since it was working locally and not in the remote host, SET NAMES weren't being set to utf8, but falling back to default latin1 and my JSON data was corrupt. this should be accepted ASAP.

**Comment by kemo** [comment]
Can't we make this conditional by having a `version_compare` for PHP? It's just the versions before `5.3.6` that require `PDO::MYSQL_ATTR_INIT_COMMAND` to set the charset.

**Comment by pocesar** [comment]
`set_charset` isnt being called at all. it needs to be called in the `connect` method, just like `MYSQL` driver. until this patch lands, the PDO driver violates the principle of least surprise. setting charset in the config is expected to be applied automatically when the connect happens.

**Comment by kemo** [comment]
@pocesar I fully agree, my reference to version_compare (for PHP < 5.3.6) is to another discussion about this same issue (which led to only including this into the docs, not really solving the problem)

**Pull request merged**
