### PR TITLE
Combine config reader and writer into a single class

### PR DESCRIPTION
**Pull request by shadowhand**
Without this change, it is nearly impossible to extend both the reader and writer. I have no idea what the author was thinking (teehee) because this class is definitely cannot be extended as written.

It also allows for using something other than `serialize` for encoding and decoding config values by exposing protected `_encode` and `_decode` methods that can be modified by extensions.

### CODE REVIEW

**Comment by enov** [comment]
@shadowhand sorry to close, maybe you want to target this towards `3.4/develop`?

**Comment by shadowhand** [comment]
I don't, this affects 3.3 too.

**Comment by enov** [comment]
Alright, if this is a bug and this is the way it should be fixed, then probably it should go to `3.3/develop`?

**Comment by shadowhand** [comment]
See #77

**Pull request closed without merging**
